[package]
name = "callora-vault"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
callora-validators = { path = "../validators" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
rand = "0.8"
proptest = { version = "1", default-features = false, features = ["std", "alloc"] }
callora-settlement = { path = "../settlement" }
callora-revenue-pool = { path = "../revenue_pool" }
