[package]
name = "callora-topics"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
callora-validators = { path = "../validators" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
