# SPDX-License-Identifier: MIT
[package]
name = "creditra-borrow-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.creditra-credit]
path = "../../credit"

# Prevent this from interfering with workspaces
[workspace]

[[bin]]
name = "main"
path = "targets/main.rs"
doc = false
